{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "2be406aa-e045-4919-938e-8cca92f1b49f",
   "metadata": {},
   "outputs": [],
   "source": [
    "%gui tk\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ac7fa7c4-4634-492a-8a28-ec94a19f32ba",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import filedialog, Label, Button\n",
    "from PIL import ImageTk, Image\n",
    "import numpy\n",
    "from keras.models import load_model\n",
    "\n",
    "def run_gui():\n",
    "    model = load_model('my_model.h5')\n",
    "\n",
    "    classes = {1: 'Speed limit (20km/h)', 2: 'Speed limit (30km/h)', 3: 'Speed limit (50km/h)'}  # Shortened\n",
    "\n",
    "    top = tk.Tk()\n",
    "    top.geometry('800x600')\n",
    "    top.title('Traffic sign classification')\n",
    "    top.configure(background='#CDCDCD')\n",
    "\n",
    "    label = Label(top, background='#CDCDCD', font=('arial', 15, 'bold'))\n",
    "    sign_image = Label(top)\n",
    "\n",
    "    def classify(file_path):\n",
    "        image = Image.open(file_path).resize((30, 30))\n",
    "        image = numpy.expand_dims(image, axis=0)\n",
    "        image = numpy.array(image)\n",
    "        pred = model.predict_classes([image])[0]\n",
    "        sign = classes.get(pred + 1, \"Unknown Sign\")\n",
    "        label.configure(foreground='#011638', text=sign)\n",
    "\n",
    "    def show_classify_button(file_path):\n",
    "        classify_b = Button(top, text=\"Classify Image\", command=lambda: classify(file_path), padx=10, pady=5)\n",
    "        classify_b.configure(background='#364156', foreground='white', font=('arial', 10, 'bold'))\n",
    "        classify_b.place(relx=0.79, rely=0.46)\n",
    "\n",
    "    def upload_image():\n",
    "        file_path = filedialog.askopenfilename()\n",
    "        if file_path:\n",
    "            uploaded = Image.open(file_path)\n",
    "            uploaded.thumbnail((top.winfo_width() / 2.25, top.winfo_height() / 2.25))\n",
    "            im = ImageTk.PhotoImage(uploaded)\n",
    "            sign_image.configure(image=im)\n",
    "            sign_image.image = im\n",
    "            label.configure(text='')\n",
    "            show_classify_button(file_path)\n",
    "\n",
    "    upload = Button(top, text=\"Upload an image\", command=upload_image, padx=10, pady=5)\n",
    "    upload.configure(background='#364156', foreground='white', font=('arial', 10, 'bold'))\n",
    "\n",
    "    upload.pack(side=tk.BOTTOM, pady=50)\n",
    "    sign_image.pack(side=tk.BOTTOM, expand=True)\n",
    "    label.pack(side=tk.BOTTOM, expand=True)\n",
    "    heading = Label(top, text=\"Know Your Traffic Sign\", pady=20, font=('arial', 20, 'bold'))\n",
    "    heading.configure(background='#CDCDCD', foreground='#364156')\n",
    "    heading.pack()\n",
    "\n",
    "    top.mainloop()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "01cccc95-53e9-4d2a-a7fb-13042c92cbba",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\AppData\\Local\\Temp\\ipykernel_3496\\26166768.py\", line 39, in upload_image\n",
      "    sign_image.configure(image=im)\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1722, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1712, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: image \"pyimage1\" doesn't exist\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\AppData\\Local\\Temp\\ipykernel_3496\\26166768.py\", line 39, in upload_image\n",
      "    sign_image.configure(image=im)\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1722, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1712, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: image \"pyimage2\" doesn't exist\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\AppData\\Local\\Temp\\ipykernel_3496\\26166768.py\", line 39, in upload_image\n",
      "    sign_image.configure(image=im)\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1722, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1712, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: image \"pyimage3\" doesn't exist\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\AppData\\Local\\Temp\\ipykernel_3496\\26166768.py\", line 39, in upload_image\n",
      "    sign_image.configure(image=im)\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1722, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1712, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: image \"pyimage4\" doesn't exist\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\AppData\\Local\\Temp\\ipykernel_3496\\26166768.py\", line 39, in upload_image\n",
      "    sign_image.configure(image=im)\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1722, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\dell\\anaconda3\\Lib\\tkinter\\__init__.py\", line 1712, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: image \"pyimage5\" doesn't exist\n"
     ]
    }
   ],
   "source": [
    "run_gui()\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9f2ca783-612f-4d7b-931c-371499552199",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
